/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;
import java.io.IOException;


public class App {

    public static void main(String[] args) throws IOException {

        if (args.length < 3) {
            System.out.println("Invalid argument");
        }

        String PATH = args[0];
        String OUTPUTPATH = args[1];
        String transform = args[2];

        BitmapTransformer blackToGrey = new BitmapTransformer();

        switch (transform) {
            case "transform-grey":
                blackToGrey.changeToGrey(PATH, OUTPUTPATH);
                break;

            case "transform-flip":
                blackToGrey.flipImage(PATH,OUTPUTPATH);
                break;


            case "transform-resize":
                System.out.println(blackToGrey.resize(PATH,OUTPUTPATH));
                break;
        }


    }
}
